### ISSUE TITLE
Switch from hash URLs to history API

### ISSUE THREAD

**Issue by fadeev** [cosmos/atlas#33]
Right now URLs have `/#/` symbol, which is a bit redundant because every browser in existence supports session history management.

https://caniuse.com/history

**Comment by alexanderbez** [comment]
@fadeev how do I go about resolving this?

**Comment by fadeev** [comment]
It's just a matter of adding one line to the `VueRouter` constructor object:

```
mode: "history"
```

https://router.vuejs.org/guide/essentials/history-mode.html

However, I've looked through the codebase and noticed that the frontend is served by the same process as the API (`atlas server`). That's less than ideal because the Go server handles all URLs as paths to static files, e.g. `/foo/bar` is looking for `web/dist/foo/bar/index.html`, where it should be serving `web/dist/index.html`. Anyways, services like Netlify handle this automatically and it's just a good practice to separate (a more demanding dynamic) API server from a static frontend.

**Comment by alexanderbez** [comment]
This is originally how I had it and will revert to this model. I made these changes because it was easier to run in DigitalOcean's App instance.

**Comment by alexanderbez** [comment]
@fadeev now that I split up the API server and the webapp, the Vue webapp isn't sending session cookies to the API. I suppose this is something to do with axios. Do I need to any special wiring here?

**Comment by fadeev** [comment]
Yep, that's up to the backend server to specify CORS rules.

**Comment by alexanderbez** [comment]
Fixed it. `*` doesn't work with `withCredentials: true` -- you have explicitly set the allowed origins.

**Comment by alexanderbez** [comment]
@fadeev I've attempted to switch to `mode: "history"` in #38, but I'm having trouble with the vue-router. Specifically, `queryModules`, where I push a route, `this.$router.push({name: "search-results", query: { q: this.searchCriteria }});`, that loads the search results component. The component loads, but it seems the page is refreshed and the query param is gone so there is nothing to query for.

Is `this.$router.push()` not valid with `"history"` mode?

**Comment by fadeev** [comment]
> Is this.$router.push() not valid with "history" mode?

You can use `push` with "history".

I am still getting CORS issue and signing in doesn't work. It's just redirecting back to`:8080`. (I'm running Atlas on 8080 and a frontend on 8081).

**Comment by alexanderbez** [comment]
@fadeev the PR was merged to `main`. Please try again. I've had zero issues thus far. I think we're ready for deploying this soon.
